spring:
  application:
    name: capstone
  datasource:
    url : jdbc:mysql://capstone.cbqqi6o00vb2.ap-northeast-2.rds.amazonaws.com/capstone
    username : admin
    password : dream61398
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace
server:
  port: 80
